/* eslint-disable cypress/no-async-tests */
import { test } from '@playwright/test'

test.describe('Full test of the Portuguese Stone Harbor demo', () => {
    test('Checks that Stone Harbor Portuguese works', async ({ page }) => {
        await page.goto('/stone-harbor-pt')
        await page.getByRole('link').filter({ hasText: 'roupas' }).click()
        await page.getByRole('link').filter({ hasText: 'anel' }).click()
        await page.getByRole('link').filter({ hasText: 'Nancy?' }).click()
        await page.getByRole('link').filter({ hasText: 'Nadine?' }).click()
        cy.contains('casamento')
        await page.getByRole('link').filter({ hasText: 'aparência' }).click()
        await page.getByRole('link').filter({ hasText: 'o escaldão a pelar' }).click()
        cy.contains('consegues algumas pistas')
        cy.contains('passar tempo ao ar livre')
        cy.contains('anel também ficou esquecido')
        await page.getByRole('link').filter({ hasText: 'cartão' }).click()
        cy.contains('cartão, que viras e lês')
        await page.getByRole('link').filter({ hasText: 'luva' }).click()
        await page.getByRole('link').filter({ hasText: 'luva' }).click()
        cy.contains('e tudo muda')
        cy.get('img').should('have.attr', 'alt').and('contains', 'Um escritório pequeno')
        await page.getByRole('link').filter({ hasText: 'bibelôs' }).click()
        await page.getByRole('link').filter({ hasText: 'fotografia' }).click()
        cy.contains('objetos pessoais')
        cy.contains('Examinas a imagem.')
        await page.getByRole('link').filter({ hasText: 'luva zangada' }).click()
        cy.contains('Healey foi assassinado.')
    })
})
